#!/bin/bash

unset TMOUT

#"install" node for uglifyjs
if ! [ -d "$OPENSHIFT_DATA_DIR/node-v4.2.1-linux-x64" ]; then
	echo "Installing node.js in $OPENSHIFT_DATA_DIR"
	mv -u "$OPENSHIFT_REPO_DIR/.openshift/data/node-v4.2.1-linux-x64" "$OPENSHIFT_DATA_DIR"
	ln -s "$OPENSHIFT_DATA_DIR/node-v4.2.1-linux-x64/bin/node" "$HOME/.gem/bin/"
	ln -s "$OPENSHIFT_DATA_DIR/node-v4.2.1-linux-x64/bin/npm" "$HOME/.gem/bin/"
	mkdir "$OPENSHIFT_DATA_DIR/node_modules"
	echo "cache=$OPENSHIFT_DATA_DIR/node_modules/.npm
	prefix=$OPENSHIFT_DATA_DIR" > "$OPENSHIFT_DATA_DIR/node-v4.2.1-linux-x64/etc/npmrc"
fi

pushd "$OPENSHIFT_DATA_DIR"
"$HOME/.gem/bin/npm" install uglifyjs
popd

if ! [ -f "$HOME/.gem/bin/uglifyjs" ]; then
	ln -s "$OPENSHIFT_DATA_DIR/node_modules/uglifyjs/bin/uglifyjs" "$HOME/.gem/bin/"
fi

bundle exec rake db:migrate RAILS_ENV="production"

if ! [ -d "$OPENSHIFT_REPO_DIR/public/assets" ] || [ -f "$OPENSHIFT_REPO_DIR/.openshift/markers/force_clean_build" ]; then
    RAILS_ENV=production bundle exec rake assets:precompile
fi

